server:
  port: 9900
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo001?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 1 #操作0号数据库
    jedis: #redis连接池
     pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #最大阻塞等待时间
        max-idle: 4 #最大空闲连接
        min-idle: 0 #最小空闲连接
  ###rabbitmq
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 1s #设置MQ链接超时时间
    template:
      retry:
        enabled: true #开启超时重试机制
        initial-interval: 1000ms #失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数,下次等待时长
        max-attempts: 3 #最大重试次数

    publisher-confirm-type: correlated # 开启MQ异步回调机制,返回回执信息 ack nack
    publisher-returns: true # 开启 return机制

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exam.spring.*.entity
logging:
  level:
    com.exam: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

app:
  value: "5"